from fastapi import APIRouter, HTTPException, status
from models.schemas import (
    HealthResponse,
    IngestRequest,
    IngestResponse,
    QueryRequest,
    QueryResponse
)
from rag.pipeline import RAGPipeline

router = APIRouter()
rag_pipeline: RAGPipeline = None


def get_pipeline() -> RAGPipeline:
    global rag_pipeline
    if rag_pipeline is None:
        rag_pipeline = RAGPipeline()
    return rag_pipeline


@router.get("/health", response_model=HealthResponse, summary="Service Health Check")
async def health_check():
    """Health check endpoint to verify backend service status."""
    return HealthResponse(status="healthy", version="v1")


@router.post("/ingest", response_model=IngestResponse, summary="Ingest Document or Directory")
async def ingest_document(request: IngestRequest = IngestRequest()):
    """
    Extracts text from PDF/TXT documents, chunks it with metadata, generates embeddings,
    and stores vectors in Qdrant. Optionally deletes old embeddings first when reset_collection=True.
    """
    try:
        pipeline = get_pipeline()
        response = pipeline.ingest_document(
            file_path_str=request.file_path,
            reset_collection=request.reset_collection
        )
        return response
    except FileNotFoundError as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ingestion failed: {str(e)}"
        )


@router.post("/query", response_model=QueryResponse, summary="Query RAG System")
async def query_rag(request: QueryRequest):
    """
    Accepts a user question, retrieves the top 5 relevant document chunks,
    and returns a grounded answer generated by Gemini with source citations.
    """
    if not request.question.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Question cannot be empty."
        )

    try:
        pipeline = get_pipeline()
        response = pipeline.query(
            question=request.question,
            conversation_id=request.conversation_id
        )
        return response
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Query execution failed: {str(e)}"
        )
